Added the new videos
semaphore-protocol/semaphore pull request #613
Opened 2024-02-06 13:43 UTC by dicethedev

Fix the Add these new videos to the Semaphore website #610

2024-02-06 14:00 UTC, vplasencia requested changes
Hey @dicethedev 

Thank you so much! Great work! ✨

I added some comments to update an event name, a title and the thumbnails.

You can click on `Commit Suggestion` to update them automatically.

2024-02-06 14:00 UTC, vplasencia commented on apps/website/src/data/videos.json
> +        "eventName": "Devconnect 2023",
```suggestion
        "eventName": "PROGCRYPTO - Devconnect 2023",
```

2024-02-06 14:00 UTC, vplasencia commented on apps/website/src/data/videos.json
> +        "thumbnail": "https://img.youtube.com/vi/4e4EAdu0WVg/0.jpg"
```suggestion
        "thumbnail": "https://img.youtube.com/vi/WEKqycIMmLY/0.jpg"
```

2024-02-06 14:00 UTC, vplasencia commented on apps/website/src/data/videos.json
> +        "title": "The Power of Anonymity",
```suggestion
        "title": "Semaphore: The power of anonymity",
```

2024-02-06 14:00 UTC, vplasencia commented on apps/website/src/data/videos.json
> +        "thumbnail": "https://img.youtube.com/vi/4e4EAdu0WVg/0.jpg"
```suggestion
        "thumbnail": "https://img.youtube.com/vi/tx1Xglf07yE/0.jpg"
```

2024-02-08 07:54 UTC, dicethedev commented
> yarn prettier:write

just push update @vplasencia

2024-02-08 10:13 UTC, vplasencia approved these changes
Thank you @dicethedev ! ✨

2024-02-08 10:58 UTC, cedoor approved these changes

2024-02-08 10:59 UTC, merged