Update `cli-template-contracts-hardhat`
semaphore-protocol/semaphore pull request #651
Opened 2024-02-25 22:45 UTC by vplasencia

## Related Issue(s)

Closes #646

## Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] I have made corresponding changes to the documentation
-   [x] My changes generate no new warnings
-   [x] I have run `yarn prettier` and `yarn lint` without getting any errors
-   [x] I have added tests that prove my fix is effective or that my feature works
-   [x] New and existing unit tests pass locally with my changes
-   [x] Any dependent changes have been merged and published in downstream modules

2024-02-27 09:38 UTC, 0xjei approved these changes
Great work! :fire: 

I noticed the following [error](https://hardhat.org/hardhat-runner/docs/errors#HH308) when running `yarn dev`. This should be related to the `localhost` parameter. Let me approve the PR but could you please check before merging? Thank you! 

![image](https://github.com/semaphore-protocol/semaphore/assets/20580910/6882fa95-08d0-48bd-957b-8522d9698b86)

2024-02-27 09:45 UTC, vplasencia commented
Hey! @0xjei thanks for the review. Yes, the project is prepared to use `npm` instead of `yarn`. To use `yarn`, you need to change some configs first. The other two templates are using `yarn` now, but I'm changing the config to use `npm` by default in a way that it's easy to use other package managers too with minimal changes. 

The idea is to have `npm` by default in all the templates and add info in the docs on how devs can easily add other package managers like `yarn` and `pnpm`.

2024-02-27 09:52 UTC, 0xjei commented
> Hey! @0xjei thanks for the review. Yes, the project is prepared to use `npm` instead of `yarn`. To use `yarn`, you need to change some configs first. The other two templates are using `yarn` now, but I'm changing the config to use `npm` by default in a way that it's easy to use other package managers too with minimal changes.
> 
> The idea is to have `npm` by default in all the templates and add info in the docs on how devs can easily add other package managers like `yarn` and `pnpm`.

Do you think that really makes sense? It could be confusing as the whole project uses `yarn` as the default!

2024-02-27 09:57 UTC, 0xjei commented
> > Hey! @0xjei thanks for the review. Yes, the project is prepared to use `npm` instead of `yarn`. To use `yarn`, you need to change some configs first. The other two templates are using `yarn` now, but I'm changing the config to use `npm` by default in a way that it's easy to use other package managers too with minimal changes.
> > The idea is to have `npm` by default in all the templates and add info in the docs on how devs can easily add other package managers like `yarn` and `pnpm`.
> 
> Do you think that really makes sense? It could be confusing as the whole project uses `yarn` as the default!

BTW, I'm still getting the same error with `npm run dev` too

2024-02-27 13:35 UTC, vplasencia commented
> Do you think that really makes sense? It could be confusing as the whole project uses yarn as the default!

The idea is to create the templates as generic as possible in a way that dev can use the package manager they prefer.

What do you think that would be better?

2024-02-27 16:18 UTC, 0xjei approved these changes
Works fine now and makes sense to use `yarn` V4 by default as we internally discussed. Thank you! :blush:

2024-02-27 16:44 UTC, cedoor requested changes

2024-02-27 16:44 UTC, cedoor commented on packages/cli-template-contracts-hardhat/.eslintignore
> +snark-artifacts
This folder shouldn't be part of this template anymore. So shouldn't be necessary to have it here

2024-02-27 16:44 UTC, cedoor commented on packages/cli-template-contracts-hardhat/.eslintrc.json
> +        "project": ["./tsconfig.json", "./packages/**/tsconfig.json"]
This isn't a monorepo. `"./packages/**/tsconfig.json"` is not necessary

2024-02-27 16:44 UTC, cedoor commented on packages/cli-template-contracts-hardhat/.eslintignore
> +cli-template-*
This is not necessary here

2024-02-27 16:44 UTC, cedoor commented on packages/cli-template-contracts-hardhat/.eslintignore
> +docs
These folders shouldn't be necessary here

2024-02-27 16:44 UTC, cedoor commented on packages/cli-template-contracts-hardhat/.prettierignore
> +packages/contracts/deployed-contracts/localhost.json
Shouldn't be necessary

2024-02-27 16:44 UTC, cedoor commented on packages/cli-template-contracts-hardhat/.prettierignore
> +Verifier*.sol
There's no such a contract here

2024-02-27 16:44 UTC, cedoor commented on packages/cli-template-contracts-hardhat/.prettierignore
> +zk-artifacts
No necessary

2024-02-27 16:44 UTC, cedoor commented on packages/cli-template-contracts-hardhat/README.md
> +```
This is usually another `## Install` section in the other packages, right before the `## Usage` one.

e.g.

```md
## Install

Install the dependencies:

`` `bash
yarn
`` `

## Usage

...
```

2024-02-27 16:44 UTC, cedoor commented on packages/cli-template-contracts-hardhat/package.json
> +        "@semaphore-protocol/contracts": "^4.0.0-alpha.8"
It should be good practice to not use ^ here, as it's a dependency

2024-02-27 16:44 UTC, cedoor commented on packages/cli-template-contracts-hardhat/test/Feedback.ts
> +            const fullProof = await generateProof(users[1], group, feedback, groupId)
We can call this `proof` now, as there's no `proof.proof` anymore (it's `proof.points` now).

2024-02-27 16:44 UTC, cedoor commented on packages/cli-template-contracts-hardhat/tsconfig.json
> -    "files": ["./hardhat.config.ts"]
Not sure if it includes these folders by default

2024-02-27 16:44 UTC, cedoor commented on packages/cli-template-contracts-hardhat/package.json
> +        "tsconfig.json"
This list is missing: `README.md`, `.yarn/`, `.yarnrc.yml`

It doesn't need: `scripts/`

2024-02-27 16:44 UTC, cedoor commented on packages/cli-template-contracts-hardhat/package.json
> -        "prepublish": "tar -czf files.tgz .gitignore"
We need this

2024-02-28 09:21 UTC, cedoor requested changes

2024-02-28 09:21 UTC, cedoor commented on packages/cli-template-contracts-hardhat/tsconfig.json
>      "include": ["scripts/**/*", "tasks/**/*", "test/**/*", "build/typechain/**/*", "types/**/*"],
```suggestion
    "include": ["scripts/**/*", "tasks/**/*", "test/**/*", "typechain-types/**/*"],
```

The same change needs to be applied to the other templates.

2024-02-28 09:46 UTC, cedoor approved these changes

2024-02-28 09:47 UTC, merged