New branch
semaphore-protocol/semaphore pull request #854
Opened 2024-09-09 16:03 UTC by timou0911

## Description

Create a CLI foundry template with a sample contract, a deploy script, and tests for it.
The contract itself is the same as in [CLI hardhat template](https://github.com/semaphore-protocol/semaphore/tree/main/packages/cli-template-contracts-hardhat).

## Related Issue(s)

Closes [#646 ](https://github.com/semaphore-protocol/semaphore/issues/646)

## Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings
-   [x] I have run `yarn format` and `yarn lint` without getting any errors
-   [x] I have added tests that prove my fix is effective or that my feature works
-   [x] New and existing unit tests pass locally with my changes

2024-09-10 14:57 UTC, sripwoud requested changes
Thanks @timou0911 that's a great start, I could successfully test executing some of the tasks (`make {build,test,coverage,gas-report...}`).

I think there is still some work left to do (especially [here](https://github.com/semaphore-protocol/semaphore/blob/main/packages/cli/src/index.ts)).
The CLI template should become an npm package that we will publish so it can be selected as template when using the `create` command of the CLI.
![image](https://github.com/user-attachments/assets/15397134-d177-4226-8905-8fa8b46547de).

Here is for instance a [PR](https://github.com/semaphore-protocol/semaphore/pull/299) that added a previous template.

2024-09-10 14:57 UTC, sripwoud commented on packages/cli-template-contracts-foundry/Makefile
I personally love `Makefile` as a task runner.
But I am wondering if it is appropriate for this repo.
This repo is very "node ecosystem" oriented. So we run tasks with `yarn`.  
On one side I agree it may not make much sense to use `yarn` as a task runner for a template that does not include any `js,ts` files, making `make` a good choice.
One the other side, for the sake of consistency maybe we should stick to `yarn`: meaning all these make tasks belong rather in package.json `scripts`. And eventually we need a package.json in order to publish the template as an npm package... so...

What do you think @vplasencia @cedoor ?

2024-09-11 15:09 UTC, cedoor commented on packages/cli-template-contracts-foundry/Makefile
I agree! As soon as we have 1 non-NPM package only we should make it a NPM package. If there are many other non-NPM packages we can think of a system to download templates that is more language-agnostic.

2024-09-11 15:56 UTC, vplasencia commented on packages/cli-template-contracts-foundry/Makefile
Good question. Regarding if it's better to use Makefile or yarn, I think it depends on what developers prefer when using Foundry. If most devs prefer to use Makefile, we should provide the Foundry template with Makefile and if they prefer yarn (npm, pnpm) we should provide the Foundry template with yarn. If there are no strong opinions on that we could decide one. 

If we have to decide one, I see pros and cons. I think for just contracts, Makefile could be lighter and easier to add but for bigger projects yarn (npm, pnpm) could be better. 

I have seen projects using both, so another alternative to discuss could be if it's better to add both.

2024-09-12 10:07 UTC, cedoor commented on packages/cli-template-contracts-foundry/Makefile
What about having `Makefile` as a task runner and a `package.json` to make it compatible/downloadable with our CLI?

2024-09-12 10:20 UTC, vplasencia commented on packages/cli-template-contracts-foundry/Makefile
We could also add a `package.json` to download the template and then remove it after it's downloaded, the same way we create the `yarn.lock` file but removing a file instead of creating it. 

Or if we keep the `package.json` and add the scripts so that people decide the one they prefer and remove the Makefile or the `package.json` and `yarn.lock` files. 

What do you think?

2024-09-20 14:42 UTC, cedoor commented on packages/cli-template-contracts-foundry/Makefile
I tend to prefer the first option.

@sripwoud ?

2024-09-22 08:54 UTC, sripwoud commented on packages/cli-template-contracts-foundry/Makefile
Yes let's go with the option of keeping the `Makefile` and removing the `package.json` after it having been downloaded. (That's was the 1st option right?)

2024-10-03 11:48 UTC, cedoor commented on packages/cli-template-contracts-foundry/Makefile
@timou0911 @sripwoud  Is this PR ready to be merged?

2024-10-03 15:42 UTC, timou0911 commented on packages/cli-template-contracts-foundry/Makefile
Sorry, I was busy in the past few weeks. I will start handling it next week.

2024-10-03 16:21 UTC, cedoor commented on packages/cli-template-contracts-foundry/Makefile
No problem!

2024-11-07 03:45 UTC, jimmychu0807 commented
@timou0911 @csiejimmyliu dear Taiwan fellows, may I pick up this PR and continue where it left off?

2024-11-07 14:41 UTC, timou0911 commented
> @timou0911 @csiejimmyliu dear Taiwan fellows, may I pick up this PR and continue where it left off?

Sure. I apologize for not being able to complete this issue sooner due to my busy schedule.
The tasks left are:
1. Make this template an npm package.
2. Keep the Makefile and remove the package.json after it has been downloaded. (Please refer to the discussion above for details)

2024-11-22 04:45 UTC, cedoor commented
Hi @jimmychu0807, be sure to create a branch from this PR, so that we can merge it here.

2024-11-29 07:08 UTC, jimmychu0807 commented
> Hi @jimmychu0807, be sure to create a branch from this PR, so that we can merge it here.

I tried to do this, and ended up with a new PR #905. If this is important to fix, could you point me to the doc? Thanks.

2024-12-02 07:37 UTC, cedoor commented
@jimmychu0807 That PR is fine, thanks!

2024-12-17 13:54 UTC, vplasencia commented
Closing this PR as it was continued and completed here: https://github.com/semaphore-protocol/semaphore/pull/905

Thank you very much @timou0911 for the great work ✨

@gitpoap-bot @timou0911

2024-12-17 13:54 UTC, closed without merging