chore: fix 404 status URL
semaphore-protocol/semaphore pull request #917
Opened 2024-12-07 07:49 UTC by hanghuge

## Description

 fix 404 status URL

## Related Issue(s)

## Other information

## Checklist

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] My changes generate no new warnings
-   [ ] I have run `yarn format` and `yarn lint` without getting any errors
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes

2024-12-10 17:12 UTC, cedoor approved these changes

2024-12-10 17:13 UTC, cedoor requested changes
These links should actually point to the `v3.15.2` tag.

https://github.com/semaphore-protocol/semaphore/blob/v3.15.2/packages/contracts/contracts/base/SemaphoreVerifier.sol

2025-01-15 11:06 UTC, hanghuge commented
> These links should actually point to the `v3.15.2` tag.
> 
> https://github.com/semaphore-protocol/semaphore/blob/v3.15.2/packages/contracts/contracts/base/SemaphoreVerifier.sol

Sorry for making the changes so late. 

Please review again.

2025-01-20 12:43 UTC, cedoor approved these changes

2025-01-20 12:43 UTC, merged