Add new article
semaphore-protocol/semaphore pull request #918
Opened 2024-12-09 12:26 UTC by zanastas

Added new blog post "Getting Started with Semaphore: Building Privacy-Preserving dApps on Ethereum" https://mirror.xyz/0xBE98D44c29D179588b7E717Db8898529e5cD770F/5Xlv1jzwJKfKgP-m257kjivBlUIM_cwTzsmpf9F0Su8

2024-12-09 18:20 UTC, aguzmant103 requested changes
@zanastas do you think you can include the url without the referrer link? I believe it should work the same:

https://mirror.xyz/0xBE98D44c29D179588b7E717Db8898529e5cD770F/5Xlv1jzwJKfKgP-m257kjivBlUIM_cwTzsmpf9F0Su8

Otherwise it looks good! Thanks for contributing with this article

2025-01-22 03:43 UTC, zanastas commented
Hello @aguzmant103, sorry for the delay, this article link submitted above (https://mirror.xyz/0xBE98D44c29D179588b7E717Db8898529e5cD770F/5Xlv1jzwJKfKgP-m257kjivBlUIM_cwTzsmpf9F0Su8 ) already does not have referral link (the first part is the author's ID, and the second part direct to the article). 

For a comparison, a link with referral link would be this https://mirror.xyz/0xBE98D44c29D179588b7E717Db8898529e5cD770F/5Xlv1jzwJKfKgP-m257kjivBlUIM_cwTzsmpf9F0Su8?referrerAddress=0x6b5153C71D6Bb6E62464987646BF4D2156B47158

2025-01-27 12:02 UTC, vplasencia requested changes
Hey @zanastas! Thank you very much for this PR. I just left one comment.

2025-01-27 12:02 UTC, vplasencia commented on apps/website/src/data/articles.json
> +        "url": "https://mirror.xyz/0xBE98D44c29D179588b7E717Db8898529e5cD770F/5Xlv1jzwJKfKgP-m257kjivBlUIM_cwTzsmpf9F0Su8?referrerAddress=0xBE98D44c29D179588b7E717Db8898529e5cD770F"
```suggestion
        "url": "https://mirror.xyz/0xBE98D44c29D179588b7E717Db8898529e5cD770F/5Xlv1jzwJKfKgP-m257kjivBlUIM_cwTzsmpf9F0Su8"
```

2025-01-28 09:14 UTC, zanastas commented
> Hey @zanastas! Thank you very much for this PR. I just left one comment.

Ok I have accepted the change- thank you!

2025-01-28 23:03 UTC, vplasencia approved these changes

2025-01-28 23:04 UTC, merged