fix: clean node_modules before build contracts
semaphore-protocol/semaphore pull request #934
Opened 2024-12-22 13:20 UTC by Dozie2001

## Description

## Related Issue(s)

Close #915 
## Other information

## Checklist

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] My changes generate no new warnings
-   [x] I have run `yarn format` and `yarn lint` without getting any errors
-   [x] I have added tests that prove my fix is effective or that my feature works
-   [x] New and existing unit tests pass locally with my changes

2025-01-09 21:37 UTC, Dozie2001 commented
@cedoor still waiting on a review

2025-01-09 21:39 UTC, vplasencia commented
Hey @Dozie2001! Thank you for this PR. I will review it asap.

2025-01-29 22:04 UTC, vplasencia requested changes
Hey @Dozie2001! Thank you for this PR. The branch has some conflicts because the subgraph dependencies were updated recently.

It looks like with the new version of the packages in the subgraph app, this issue and the one that was solved in this PR: https://github.com/semaphore-protocol/semaphore/pull/884 are not issues anymore. 

It means that the changes added to this PR are no longer necessary. 

What about updating this branch with the main branch changes (solving the conflicts) and undo the changes of this PR: https://github.com/semaphore-protocol/semaphore/pull/884/files in your PR?

2025-02-01 12:50 UTC, Dozie2001 commented
Will do

2025-02-02 17:49 UTC, closed without merging